BotSelfConfig:
  host: "127.0.0.1"
  port: 23333
  debug: false
  superusers: [ "1303030112" ]
  nickname: [ "AL-1S", "AL1S", "al-1s", "al1s", "ALICE", "Alice", "alice", "天童爱丽丝", "爱丽丝", "アリス", "天童アリス" ]
  command_start: [ "", "/" ]
  command_sep: [ "." ]
  session_expire_timeout: 60
  proxy: ""  # 请参考文档

InlineGoCQHTTP:
  enabled: true
  accounts: # 可多个账号，具体请参考文档
    - uin: 2242777106
      password: ""
      protocol: 5 # 0:Default, 1:Android Phone, 2:AndroidWatch, 3:MacOS, 4:QiDian, 5:iPad
  download_domain: "github.com"
  download_version: "v1.0.0-rc1"

BotStatus:
  server_status_only_superusers: true
  server_status_cpu: false
  server_status_per_cpu: false
  server_status_memory: false
  server_status_disk: true

YgoCard:

AiDrawer:
  wenxin_ak: "G1qqnpiVCq0FgT7lss22duBsoeLsBexX"
  wenxin_sk: "Uaxz9R90mQfMDBhYQKHGnnS5MmKk6ax7"
  wenxin_cd_time: 60
  wenxin_image_count: 3
  wenxin_manager_list: [ "1303030112" ]

HikariImageSearch:
  hikari_search_api: "https://hikari.obfs.dev"
  hikari_search_max_results: 2
  hikari_search_withdraw: 30

TarotDivination:
  chain_reply: true
  nickname: [ "AL-1S", "AL1S", "al-1s", "al1s", "ALICE", "Alice", "alice", "天童爱丽丝", "爱丽丝", "アリス", "天童アリス" ]



